-- Seed 50+ system exercises (user_id IS NULL = visible to all)
INSERT INTO exercises (name, muscle_group, equipment, is_custom) VALUES
  ('Barbell Bench Press', 'Chest', 'Barbell', false),
  ('Incline Barbell Press', 'Chest', 'Barbell', false),
  ('Decline Barbell Press', 'Chest', 'Barbell', false),
  ('Dumbbell Bench Press', 'Chest', 'Dumbbell', false),
  ('Incline Dumbbell Press', 'Chest', 'Dumbbell', false),
  ('Dumbbell Flyes', 'Chest', 'Dumbbell', false),
  ('Cable Crossover', 'Chest', 'Cable', false),
  ('Push-Ups', 'Chest', 'Bodyweight', false),
  ('Dips', 'Chest', 'Bodyweight', false),
  ('Machine Chest Press', 'Chest', 'Machine', false),
  ('Barbell Back Squat', 'Legs', 'Barbell', false),
  ('Front Squat', 'Legs', 'Barbell', false),
  ('Leg Press', 'Legs', 'Machine', false),
  ('Romanian Deadlift', 'Legs', 'Barbell', false),
  ('Conventional Deadlift', 'Legs', 'Barbell', false),
  ('Sumo Deadlift', 'Legs', 'Barbell', false),
  ('Bulgarian Split Squat', 'Legs', 'Dumbbell', false),
  ('Walking Lunges', 'Legs', 'Dumbbell', false),
  ('Leg Extension', 'Legs', 'Machine', false),
  ('Leg Curl', 'Legs', 'Machine', false),
  ('Calf Raises', 'Legs', 'Machine', false),
  ('Hip Thrust', 'Legs', 'Barbell', false),
  ('Goblet Squat', 'Legs', 'Dumbbell', false),
  ('Barbell Row', 'Back', 'Barbell', false),
  ('Pendlay Row', 'Back', 'Barbell', false),
  ('Dumbbell Row', 'Back', 'Dumbbell', false),
  ('Lat Pulldown', 'Back', 'Cable', false),
  ('Pull-Ups', 'Back', 'Bodyweight', false),
  ('Chin-Ups', 'Back', 'Bodyweight', false),
  ('Seated Cable Row', 'Back', 'Cable', false),
  ('T-Bar Row', 'Back', 'Barbell', false),
  ('Face Pulls', 'Back', 'Cable', false),
  ('Overhead Press', 'Shoulders', 'Barbell', false),
  ('Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell', false),
  ('Arnold Press', 'Shoulders', 'Dumbbell', false),
  ('Lateral Raises', 'Shoulders', 'Dumbbell', false),
  ('Front Raises', 'Shoulders', 'Dumbbell', false),
  ('Rear Delt Flyes', 'Shoulders', 'Dumbbell', false),
  ('Upright Row', 'Shoulders', 'Barbell', false),
  ('Barbell Curl', 'Arms', 'Barbell', false),
  ('Dumbbell Curl', 'Arms', 'Dumbbell', false),
  ('Hammer Curl', 'Arms', 'Dumbbell', false),
  ('Preacher Curl', 'Arms', 'Barbell', false),
  ('Tricep Pushdown', 'Arms', 'Cable', false),
  ('Skull Crushers', 'Arms', 'Barbell', false),
  ('Overhead Tricep Extension', 'Arms', 'Dumbbell', false),
  ('Close-Grip Bench Press', 'Arms', 'Barbell', false),
  ('Plank', 'Core', 'Bodyweight', false),
  ('Hanging Leg Raises', 'Core', 'Bodyweight', false),
  ('Cable Crunch', 'Core', 'Cable', false),
  ('Russian Twists', 'Core', 'Bodyweight', false),
  ('Ab Wheel Rollout', 'Core', 'Bodyweight', false),
  ('Farmer Walk', 'Full Body', 'Dumbbell', false),
  ('Kettlebell Swing', 'Full Body', 'Kettlebell', false),
  ('Clean and Press', 'Full Body', 'Barbell', false),
  ('Box Jumps', 'Full Body', 'Bodyweight', false),
  ('Battle Ropes', 'Full Body', 'Bodyweight', false);
